metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - memory
    - filesystem
    - process
    - network
  enabled: true
  period: 10s
  processes: ['.*']
  cpu_ticks: false

output.elasticsearch:
  hosts: ["localhost:9200"]

setup.kibana:
  host: "localhost:5601"
